FROM python:3.9-slim

RUN apt-get update && apt-get install -y coreutils supervisor

WORKDIR /app

COPY requirements.txt requirements.txt
COPY config.json /app/config.json
RUN pip install -r requirements.txt

COPY . .

RUN mkdir /logs

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]




