version: '3'

services:
  app:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SEARCH_URL=http://app:5000/api/search
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5002
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8000:5000"  # Update this line
      - "8001:8001"
    depends_on:
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
